CREATE TABLE IF NOT EXISTS platform_initial_administrator_receipts (
    command_id VARCHAR(128) PRIMARY KEY,
    request_sha256 VARCHAR(64) NOT NULL,
    user_id VARCHAR(36) NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (status = 'created'),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
